### ISSUE TITLE
How to overwrite a Module?

### ISSUE THREAD

**Issue by bneigher** [jbiskur/nestjs-utils#7]
Love this repo, I believe using these tools provide a far superior approach to writing easily manageable tests.

In exploring a simple way of setting up unit and e2e tests, I'm hoping to load in my main `AppModule` (with all of it's modules which include logging, sdk interfaces, axios api interfaces, ect) and then overwrite the ones specific to the test suite.  Was hoping there was a way to simply overwrite an entire module (as opposed to a service).  I'm not quite sure how to interpret the README and the source code on how to accomplish this.

Here is an example:
## Replace `TypeOrmModule` with Testing configuration `TypeOrmModule`

I'de like to initialize an application instance in my test suite using the `ApplicationInstanceBuilder`, then pass in a custom `NestApplicationBuilder` class.  This class contains the definitions for modules I would like to potentially overwrite.  In this case, I have a TypeORM in-memory configuration which let's my tests run against a fresh copy of the database without needing to mock data or use a database/container.

Here is my main application module:

```javascript
import { Module, CacheModule, Logger } from '@nestjs/common'
import { GraphQLModule } from '@nestjs/graphql'
import { TypeOrmModule } from '@nestjs/typeorm'
import { ApolloFederationDriver, ApolloFederationDriverConfig } from '@nestjs/apollo'
import { dotenvLoader, TypedConfigModule } from 'nest-typed-config'
import { Config } from '_common/config'
import { GQL_API_A_Module, GQL_API_B_Module, GQL_API_A_Module, GQL_API_B_Module } from "_common/modules"
import { Module, CacheModule, Logger } from '@nestjs/common'
import DataSource, { InjectedTypeOrmModuleOptions } from './ormconfig'

@Module({
  imports: [
    TypedConfigModule.forRoot({ isGlobal: true, schema: Config, load: dotenvLoader()}),
    TypeOrmModule.forRoot(InjectedTypeOrmModuleOptions), // <-- Using Real Database configs normally
    GraphQLModule.forRootAsync<ApolloFederationDriverConfig>({
      driver: ApolloFederationDriver,
      inject: [Config],
      useFactory: graphQLModuleInitFactory
    }),
    CacheModule.register({ isGlobal: true }),
    REST_API_A_Module,
    REST_API_B_Module,
    GQL_API_A_Module,
    GQL_API_B_Module,
    UsersModule
  ],
  controllers: [],
  providers: [Logger]
})
export class AppModule {}
```

The above is the module that gets used in creating the Nest App in main.ts `await NestFactory.create(AppModule)` when running the API in real environments.

Now, I have made a utility, `TestNestApplicationBuilder`, which is to be using in my tests to define any customizations I need to make to the application in the jest testing `before` configurations.. here is what I have done so far per the README typeORM configuration example:

```javascript
import { NestApplicationBuilder, ITestModuleBuilder } from '@jbiskur/nestjs-test-utilities'
import { TypeOrmModule } from '@nestjs/typeorm'
import TestingDataSource, { InjectedTypeOrmModuleOptions } from '../src/testingOrmconfig'

export default class TestNestApplicationBuilder extends NestApplicationBuilder {
  withMemoryTypeORMConnection(): this {
    this.withTestModule((builder: ITestModuleBuilder) =>
      builder.withModule(
        TypeOrmModule.forRootAsync({
          useFactory: () => InjectedTypeOrmModuleOptions,
          dataSourceFactory: async () => TestingDataSource // <- `pg-mem` TypeORM instance
        })
      )
    )
    return this
  }
}
```

And I interface with it in my .spec.ts tests like so:

```javascript
import { ApplicationInstance, ApplicationInstanceBuilder } from '@jbiskur/nestjs-test-utilities'
import { AppModule } from 'app.module'
import TestNestApplicationBuilder from '../../test/TestNestApplicationBuilder'
import { UsersService } from './users/users.service'

describe('Users', () => {
  let usersService
  beforeEach(async () => {
    const built = await new ApplicationInstanceBuilder(
      new TestNestApplicationBuilder()
        .withTestModule((builder) => builder.withModule(AppModule))
        .withMemoryTypeORMConnection()
    ).build()
    const module = built.instance
    const usersService = module.get<UsersService>(UsersService)
  })
})
```

### The Problem
Here, we have a `withMemoryTypeORMConnection` which will insert my in-memory TypeORM module into the testing app instance.. and it works fine.  *However, it collides with the _real_ TypeORM module in AppModule.*

======================

So my question is, how do I use `withOverrideProvider` to overwrite the `AppModule`'s TypeOrmModule with my Testing TypeOrmModule?  Would greatly appreciate the help

**Comment by jbiskur** [comment]
Hi, thanks for the interest in the repo :) I have looked at the testing module to find a way to override a module. I think I have found a way to do that (I only tested with simple modules, not dynamic, but if it uses metadata the same as simple modules, it should work).

I added a new release `v3.12.1` that has this `overrideModule` method in the module builder (added it to the readme, but I will include the snippet here).

```typescript
//...
        app = await new NestApplicationBuilder()
        .withTestModule((builder) => builder.withModule(TestModuleA))
         overrideModule(TestModuleA, ModuleToOverride, MockedModule)
        .build();
//...
```

Hope this helps :)

**Comment by bneigher** [comment]
@jbiskur absolutely amazing.  Thank you 100%

Here is how I changed my code for those who read this:

`TestNestApplicationBuilder.ts`

```javascript
import { NestApplicationBuilder, ITestModuleBuilder } from '@jbiskur/nestjs-test-utilities'
import { TypeOrmModule } from '@nestjs/typeorm'
import TestingDataSource, { InjectedTypeOrmModuleOptions } from '../src/testingOrmconfig'
import { AppModule } from '../src/app.module'

export default class TestNestApplicationBuilder extends NestApplicationBuilder {
  constructor() {
    super()
    this.withTestModule((builder) => builder.withModule(AppModule)) // <-- always inject AppModule
  }
  withMemoryTypeORMConnection(): this {
    this.overrideModule(
      AppModule,
      TypeOrmModule,
      TypeOrmModule.forRootAsync({
        useFactory: () => InjectedTypeOrmModuleOptions,
        dataSourceFactory: async () => TestingDataSource()
      })
    )
    return this
  }
}
```

and then in my test:

```javascript
import { ApplicationInstance, ApplicationInstanceBuilder } from '@jbiskur/nestjs-test-utilities'
import TestNestApplicationBuilder from '../../test/TestNestApplicationBuilder'
import { UsersService } from './users/users.service'

describe('Users', () => {
  let usersService
  beforeEach(async () => {
    const built = await new ApplicationInstanceBuilder(
      new TestNestApplicationBuilder().withMemoryTypeORMConnection()
    ).build()
    const module = built.instance
    const usersService = module.get<UsersService>(UsersService)
  })
})
```

I think this is a super clean approach.. Thanks for implementing this 🚀

**Comment by bneigher** [comment]
@jbuskur actually.. I don't think the DynamicModules work with the new overrideModule.. I must have missed the false success from a patch job I made in my app when breaking things...

Here is what I discovered:
In `module.builder.js`:

```javascript
overrideModule(testModule, target, nestModule) {
    const index = this.imports.findIndex((m) => {
        return m["name"] === (_.isString(testModule) ? testModule : testModule.name);
    });
    if (index > -1) {
        const module = this.imports[index];
        const imports = Reflect.getMetadata("imports", module);
        console.log(imports); // <-- HERE_A
        const targetIndex = imports.findIndex((m) => {
           console.log(m, m["name"], target.name); // <-- HERE_B
           return m["name"] === target.name 
        });
        if (targetIndex > -1) {
            Reflect.defineMetadata("imports", [...imports.slice(0, targetIndex), nestModule, ...imports.slice(targetIndex + 1)], module);
        }
        console.log(targetIndex, this.imports[targetIndex]); // <-- HERE_C
    }
    return this;
}
```

I added a few lines for debugging and noticed that for all of the modules that I have `.forRoot` or `.forRootAsync`.. or `.register` -- the module name property doesn't exist, so the targetIndex is -1

Per the AppConfig in the example I pasted above.. the output at log `HERE_A` looks like this:

```javascript
[
  {
    global: true,
    module: [class TypedConfigModule],
    providers: [ [Object] ],
    exports: [ [Object] ]
  },
  { module: [class TypeOrmModule], imports: [ [Object] ] },
  {
    module: [class GraphQLModule] { logger: [Logger] },
    imports: undefined,
    providers: [ [Object], [Object], [Object] ]
  },
  {
    global: true,
    module: [class CacheModule extends InternalModuleClass],
    providers: [ [Object] ]
  },
  [class REST_API_A_Module],
  [class REST_API_B_Module],
  [class GQL_API_A_Module],
  [class GQL_API_B_Module],
  [class UsersModule]
]
```

Without digging too deep.. looks like the class modules have names, but not the others.  I'm going to poke around inside these modules to see if there is a neat way to loop through the inner `module` property of the dynamic modules to get a handle on the name property

**Comment by bneigher** [comment]
Yea - looks like this change does it:


```javascript
const targetIndex = imports.findIndex((m) => {
  if (typeof m === "function") {
    return m["name"] === target.name
  } else if (typeof m === "object") {
    const innerModule = m.module
    return innerModule["name"] === target.name
  } else {
    // NOT SUPPORTED
    return false
  }
});
```

I'll make an MR -- would appreciate an 👁️ or 👀  when you have some time!

**Comment by bneigher** [comment]
Well, it works but it doesn't work.. I'm wondering if there is something deeper within the module that isn't getting overwritten?  I'm getting an error that I have duplicates in my Schema which is an error message I would get if I tried to add two `TypeOrmModules` with the same entities

**Comment by jbiskur** [comment]
Awesome, thanks for your contribution 😎

**Comment by bneigher** [comment]
@jbiskur do you mind publishing a new version to registry?  Getting ready for a release of this into my service, would like to point to your package

**Comment by jbiskur** [comment]
@bneigher, yea, I released a new version. Sorry about the delay :)
