### ISSUE TITLE
Re-run publish pipeline for nestjs-test-utilities v5.0.1

### ISSUE THREAD

**Issue by Mause** [jbiskur/nestjs-utils#9]
The pipeline failed for this version unfortunately: https://github.com/jbiskur/nestjs-utils/actions/runs/5325050709/job/14411070465

**Comment by jbiskur** [comment]
Sorry about that, I think that was due to a github outage at the time. I could not even try to re-run the pipelines. So I published a new release 5.0.2 where all pass.

**Comment by Mause** [comment]
Cheers!
